/** @type {import('next').NextConfig} */
const nextConfig = {
  reactStrictMode: true,
  swcMinify: true,
  images: {
    domains: ['43.205.198.135','ms-demo.credot.dev','admin.ms-ca.com'],
  },
  redirects:async()=>{
    return[
      {
        source:"/uae-introduces-country-by-country-reporting-10-facts-you-must-know",
        destination:'/',
        permanent:true
      },
      {
        source:"/world-expo-2020",
        destination:'/',
        permanent:true
      },
      {
        source:"/newsandblogss",
        destination:'/',
        permanent:true
      },
      {
        source:"/privacy-policy",
        destination:'/',
        permanent:true
      },
      {
        source:"/news-blogs1",
        destination:'/',
        permanent:true
      },
      {
        source:"/vat-health-check-copy",
        destination:'/',
        permanent:true
      },

      {
        source:"/payroll-services-1",
        destination:'/',
        permanent:true
      },

      {
        source:"/tax-residency-certificate-1",
        destination:'/',
        permanent:true
      },
      {
        source:"/vat-advisory-compliance-support-1",
        destination:'/',
        permanent:true
      },
      {
        source:"/vat-consultant-1",
        destination:'/',
        permanent:true
      },
      {
        source:"/vat-registration-1",
        destination:'/',
        permanent:true
      },
      {
        source:"/economic-substance-regulations-2",
        destination:'/',
        permanent:true
      },
      {
        source:"/country-by-country-reporting",
        destination:'/',
        permanent:true
      },
      {
        source:"/msatc-your-tax-consultant-in-abu-dhabi-uae-ms-ca-com-old",
        destination:'/',
        permanent:true
      },
      {
        source:"/team-ms-old-2",
        destination:'/',
        permanent:true
      },
      {
        source:"/our-awards-old-2",
        destination:'/',
        permanent:true
      },
      {
        source:"/work-with-us-old",
        destination:'/',
        permanent:true
      },
      {
        source:"/payroll-services-old",
        destination:'/',
        permanent:true
      },
      {
        source:"/vat-consultant-old",
        destination:'/',
        permanent:true
      },
      {
        source:"/vat-registration-deregistration-old",
        destination:'/',
        permanent:true
      },

      {
        source:"/vat-advisory-compliance-support-old",
        destination:'/',
        permanent:true
      },
      {
        source:"/vat-training-old",
        destination:'/',
        permanent:true
      },
      {
        source:"/smartup",
        destination:'/',
        permanent:true
      },
      {
        source:"/tourism-refund-scheme-old",
        destination:'/',
        permanent:true
      },
      {
        source:"/operational-audit-old",
        destination:'/',
        permanent:true
      },
      {
        source:"/taxation-old",
        destination:'/',
        permanent:true
      },
      {
        source:"/tax-residency-certificate-old",
        destination:'/',
        permanent:true
      },
      {
        source:"/corporate-finance-old",
        destination:'/',
        permanent:true
      },

        {
        source:"/strategic-review-old",
        destination:'/',
        permanent:true
      },
        {
        source:"/contact-form-test",
        destination:'/',
        permanent:true
      },
      {
        source:"/enterprise",
        destination:'/advisory',
        permanent:true
      },
      {
        source:"/financial-advisory-service",
        destination:'/advisory',
        permanent:true
      },
      {
        source:"/testimonials",
        destination:'/',
        permanent:true
      },
      {
        source:"/msatc-your-tax-consultant-in-abu-dhabi-uae-accounting-vat-icv",
        destination:'/',
        permanent:true
      },
      {
        source:"/us-expat-tax-consultant-new/",
        destination:'/',
        permanent:true
      },
    

      {
        source:"/blogtest",
        destination:'/',
        permanent:true
      },
      {
        source:"/how-we-help",
        destination:'/',
        permanent:true
      },
      {
        source:"/adgm-uae",
        destination:'/',
        permanent:true
      },
      {
        source:"/events",
        destination:'/',
        permanent:true
      },
      {
        source:"/bookkeeping-services",
        destination:'/accounting-services',
        permanent:true
      },
      {
        source:"/vat-registration-deregistration",
        destination:'/',
        permanent:true
      },
      {
        source:"/vat-health-check",
        destination:'/',
        permanent:true
      },
      {
        source:"/tourism-refund-scheme",
        destination:'/',
        permanent:true
      },
      {
        source:"/business-tax",
        destination:'/',
        permanent:true
      },
      {
        source:"/tax-residency-certificate",
        destination:'/',
        permanent:true
      }, {
        source:"/other-services",
        destination:'/',
        permanent:true
      }, {
        source:"/financial-controller-services",
        destination:'/cfo-services',
        permanent:true
      },
      {
        source:"/management-accounting",
        destination:'/',
        permanent:true
      },
      {
        source:"/complex-transactions-treatment",
        destination:'/transaction-advisory',
        permanent:true
      },
      {
        source:"/inventory-valuations",
        destination:'/business-valuation',
        permanent:true
      },
      {
        source:"/vat-advisory-compliance-support",
        destination:'/',
        permanent:true
      },
      {
        source:"/vat-training",
        destination:'/',
        permanent:true
      },
      {
        source:"/financial-statement-audits",
        destination:'/audit',
        permanent:true
      },
      {
        source:"/operational-audit",
        destination:'/audit',
        permanent:true
      },
      {
        source:"/fraud-financial-crime-investigation",
        destination:'/',
        permanent:true
      },
      {
        source:"/corporate-finance",
        destination:'/management-advisory',
        permanent:true
      },
      {
        source:"/strategic-review",
        destination:'/advisory',
        permanent:true
      },
      {
        source:"/fd-on-demand",
        destination:'/cfo-services',
        permanent:true
      },
     
      {
        source:"/feasiblity-report-and-business-plan",
        destination:'/',
        permanent:true
      },

      {
        source:"/advisory-board",
        destination:'/',
        permanent:true
      },

      {
        source:"/business-advisory-services-uae",
        destination:'/advisory',
        permanent:true
      },

      {
        source:"/startup",
        destination:'/e-commerce-startup',
        permanent:true
      },
      {
        source:"/business-scale-up",
        destination:'/e-commerce-startup',
        permanent:true
      },

      {
        source:"/business-transition-2",
        destination:'/deal-advisory',
        permanent:true
      },
     
      {
        source:"/family-business-advisory",
        destination:'/advisory',
        permanent:true
      },
     
      {
        source:"/freelancers-influencers-business-support",
        destination:'/',
        permanent:true
      },
     
      {
        source:"/cfo-a-guide-tostart-up-profitability",
        destination:'/',
        permanent:true
      }
     
    ]
  }

 }

module.exports = nextConfig