import React, { useEffect } from "react";
import AOS from "aos";
import "aos/dist/aos.css";

import Collapsible from "./Collapsibleprivacy";
import styles from "./Styles.module.css";

import Container from "../Common/Container";




function ADGM_FAQ_Service({faqData}) {
    useEffect(() => {
      AOS.init({
        duration: 1400,
        once: false,
      });
    }, []);
  
    return (
  
     
      <Container>
          <div className={`${styles.onlineBookingService_sub} ${styles.faqservice}`}>
            <div className={styles.columns} data-aos="fade-right">
              {/* <Collapsible
                open={false}
                arrow={true}
                title={
                  "What Are The DIFC Courts ?"
                }
              >
                <div>
                The DIFC courts are special courts in Dubai established to serve the international institutions operating in the city and the UAE. Created in 2004 by His Highness (Late) Sheikh Maktoum bin Rashid Al Maktoum, then Ruler of Dubai, these special courts follow the English common law system to deliver swift and independent justice for settling local and international civil and commercial disputes in Dubai.
                </div>
              </Collapsible> */}
            
              <Collapsible
                open={false}
                arrow={true}
                title={"1. Information Collection and Usage"}
              >
                <div>
                    <div style={{marginBottom:"20px"}}>
                While using our website, we may ask you to provide us with certain personally identifiable information that can be used to contact or identify you. Therefore, we may gather two types of information about you: 
                </div>
                <div style={{marginBottom:"20px"}}>
                (a) Personal information<br/><br/>
                Personal information, including but not limited to, your name, address, phone number, email address, date of birth, and payment information, may be collected from you when you voluntarily provide the same through the following methods, including but not limited to:
                <br/>
                1. participating in surveys and other promotions available on the Website.
                <br/>
2. communicating with us through the Contact Us information provided on our website, through the Customer Service Live Chat, or via telephone.
<br/>
3. interaction with us on our social media platforms (such as Facebook, Instagram, Twitter, and LinkedIn) or Website.
<br/>
4. Other sources, such as third parties, where it is reasonably necessary for our normal business practices to do so; and
                </div>
                <div style={{marginBottom:"20px"}}>
                (b) Aggregate information
                <br/><br/>
                Aggregate information is generated by MS’s systems and is not directly related to you personally. Whenever you interact with MS Products and/or Services, we automatically receive and record information and data on our server logs from your browser or device, which may include your IP address, device identification “cookie” information (please see below under “Cookies and Tracking”), the type of browser and/or device you’re using to access our Services, and the page or feature you requested. MS uses this data to improve our Products and/or Services For example, we learn how to best design the Website for visitors and understand what Products and/or Services you may prefer, and we can use that knowledge to improve the user experience for our customers.
                <br/>
                Failure to provide necessary personal information when requested may result in certain services not being available to you. MS may collect additional information from you in relation to promotions and any information you provide when corresponding with MS, such as through Customer Service Live Chat and participation in surveys.
                </div>
                  </div>
              </Collapsible>
  
              <Collapsible
                open={false}
                arrow={true}
                title={"2. Disclosure of Information"}
              >
                <div>
                <div style={{marginBottom:"20px"}}>
                MS may disclose personal information about you, provided you have granted authority for the following:
                </div>
                <div style={{marginBottom:"20px"}}>
                I. to disclose with our affiliates worldwide, licensees, and joint venture partners for the purposes described in this privacy policy.
                <br/>
II. any information that it gathers about you from third parties for the purpose of providing you with services that you request.
<br/>
III. aggregate tracking information and other information that does not personally identify you to third parties.
<br/>
IV. your personal information to third parties, when MS believes in good faith that it is required to do so by law or legal process; or
<br/>
V. your authorized personal information to third parties, which shall be obtained at the time of collecting the information from you.   
                </div>
                  </div>
              </Collapsible>
  
              <Collapsible
                open={false}
                arrow={true}
                title={"3. Use of information"}
              >
                <div>
                    <div style={{marginBottom:"20px"}}>
                    I. MS shall use the personal information it collects:
                    <br/>
II. to enhance website services, develop new features, authenticate users, and conduct data analysis and research.
<br/>
III. to verify your identity and assist you if you forget your password or login details for any of MS’s registration services.
<br/>
IV. to assist in providing the services requested by you.
<br/>
V. to provide further information to you about other websites and services that MS considers may be of interest to you.
<br/>
VI. to provide news, event-related information, and updates; you can withdraw consent at any time.
<br/>
VII. for future marketing, promotional, and publicity purposes, including to carry out direct marketing, market research, and surveys.
<br/>
VIII. for internal purposes, development and administration of our sites, data analytics, and compliance with our legal obligations, policies, and procedures.
<br/>
IX. for ensuring that you are shown the information that is most relevant to you and your interests.
<br/>
X. for the purposes of receiving and assessing complaints made against us.
<br/>
XI. to prevent and detect any misuse of or fraudulent activities; and for any other use that you authorize.
                    </div>
    <div style={{marginBottom:"20px"}}>
    MS’s use of Google Analytics is in compliance with Google’s Terms of Service and this Privacy Policy. The information generated by Google Analytics, including the user’s IP address, shall be transmitted to and stored by Google on servers in the United States. Information collected through Google Analytics does not include and is not linked to any personal information. Google shall not share the collected information with other Google products and tools. Information
    <br/>
collected permits evaluation of the use of this Website, analysis of user behaviour, and improvement of user’s experience with the Website. To obtain more information about how to opt out of Google Analytics, at https://tools.google.com/dlpage/gaoptout.
    </div>
                  </div>
              </Collapsible>
             <Collapsible
                open={false}
                arrow={true}
                title={" 4. Content Providers, Advertisers and Partners"}
              >
                <div>
                This Privacy Policy shall not be applicable to other third-party websites to which we may link, or to other companies or persons who may be listed as third-party contacts or suppliers on this Website. MS is not responsible for the data collection practices, privacy policies, or contents of other websites other than this website, including any other websites that are accessible via a link from this website. You should contact the operators of that particular website(s) directly should you wish to enquire about their privacy practices and policies before providing your personal information to any third party.
                  </div>
              </Collapsible>
              <Collapsible
                open={false}
                arrow={true}
                title={"5. Opting In and Out"}
              >
                <div>
                <div style={{marginBottom:"20px"}}>
                Should MS’s intended collection, use, or disclosure of your personal information be outside the collection, use, or disclosure set out in this Privacy Policy, MS shall provide you with the option to:
                </div>
                <div style={{marginBottom:"20px"}}>
                I. opt out and neither receive certain services nor participate in certain interactive areas; or
                <br/>
II. opt in to agree to be contacted by MS in relation to certain matters, such as notification of new features to the Websites, beta testing, or promotional activities.
                  </div>
                  </div>
              </Collapsible>
              <Collapsible
                open={false}
                arrow={true}
                title={"6. Protecting your Personal Information"}
              >
                <div>
                The security of your personal information is important to MS. We recognize industry standards and practice appropriate administrative, technical, and physical security safeguards to protect the personal information you provide on this website against accidental, unlawful, or unauthorized destruction, loss, alteration, access, unauthorized disclosure or use, and other unlawful forms of processing. To protect your personal information, we use several security techniques, including secure servers.
                  </div>
                  
              </Collapsible> 
              <Collapsible
                open={false}
                arrow={true}
                title={"7. Where do we store your Personal Data"}
              >
                <div>
                The Personal Data that we collect from you may be securely transferred to and securely stored on our databases.
                  </div>
                  
              </Collapsible> 
              <Collapsible
                open={false}
                arrow={true}
                title={"8.  Disclosure of Information Overseas"}
              >
                <div>
                We shall not transfer your collected personal information to countries other than the country in which you originally provided the information. We may disclose your personal information as required or permitted by law-to-law enforcement agencies, regulatory authorities, and governments for security and customs purposes.
                  </div>
                  
              </Collapsible> 
              <Collapsible
                open={false}
                arrow={true}
                title={"9. Holding, Correcting, and Updating Information"}
              >
                <div>
                <div style={{marginBottom:"20px"}}>  
                Your information shall be collected and managed for the purposes stated in this Privacy Policy. MS may allow other third parties to have access to your information, but only for the purposes set out in this Privacy Policy. MS shall take the measures necessary to ensure that your information is treated securely and in accordance with this Privacy Policy.
                  </div>
                  <div style={{marginBottom:"20px"}}>
                  We offer you the ability to correct or change the information collected at any time and as often as necessary, with the exception of certain data fields, which are restricted data fields and shall be marked as such on your account – for If you wish to amend a restricted data field or if you have any questions about how MS services work or regarding this Privacy Policy, please contact info@ms-ca.com.
                  </div>
                  </div>  
                  
              </Collapsible> 
              <Collapsible
                open={false}
                arrow={true}
                title={"10. Data Security"}
              >
                <div>
                    <div style={{marginBottom:"20px"}}>
                We store Personal Data in electronic, digital, and paper formats. We have put in place appropriate security measures to prevent your personal Data from being accidentally lost, used, accessed in an unauthorized way, altered, or disclosed. We have put in place procedures to deal with any suspected or actual Personal Data breach and will notify you and any applicable regulator of a breach where we are legally required to do so. Where direct communication with you will involve disproportionate effort, we may instead inform you via public communication or other similar measures that are equally effective.
                </div>
                <div style={{marginBottom:"20px"}}>
                Unfortunately, no data transmission over the internet can be guaranteed to be 100% secure. Therefore, we cannot guarantee the security of any Personal Data you transmit to us over the internet, and you do so at your own risk.  
                </div>
                <div style={{marginBottom:"20px"}}>
                If at any point you suspect or become aware of a security incident (e.g., you receive a suspicious communication from someone holding themselves out to be our employee or from an unauthorized website claiming to be affiliated with us), please forward the communication to us or report the incident by email to feedbacks@ms-ca.com.
                </div>
                <div style={{marginBottom:"20px"}}>
                MS reserves the right to change this Privacy Policy at any time without providing you notice of such changes. You undertake that your continued use of the Website constitutes your acceptance of the modified Privacy Policy, and you agree that all previous versions of the Privacy Policy are superseded by the modified version.
                  </div>
                  </div>
                  
              </Collapsible> 
              <Collapsible
                open={false}
                arrow={true}
                title={"11. Acceptance"}
              >
                <div>
                By using MS’s website, you signify your acceptance of this Policy.
                  </div>
                  
              </Collapsible> 
              <Collapsible
                open={false}
                arrow={true}
                title={"12. How to Contact Us"}
              >
                <div>
                If you have any questions or comments regarding our privacy practices, you may opt to contact us via info@ms-ca.com.
                  </div>
                  
              </Collapsible>
            </div>
          </div>
      </Container>
    );
  }
  
  export default ADGM_FAQ_Service;